django101/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',       include('social.urls', namespace='social')),
]

social/urls.py
from django.conf.urls import include, url
from social import views

urlpatterns = [
    url(r'login/', views.social_login, name='login'),
    url(r'$^',     views.index, name='index'),
    url(r'home/',  views.home, name='home'),
    url(r'post/add/', views.add_post, name="add_post"),
]

social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    date_time = models.DateTimeField(auto_now=True)
    photo = models.ImageField(null=True, blank=True)

class Comment(models.Model):
    text = models.TextField()
    poster = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    date_time = models.DateTimeField(auto_now=True) 

social/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.core.urlresolvers import reverse
from django.shortcuts import render

from social.models import Post

# Create your views here.

def index(request):
    return render(request, 'social/index.html')

# original View (==controller)
# def social_login(request):
#     pass

def social_login(request):
   user = authenticate(username=request.POST['username'], password=request.POST['password'])
   if user is not None:
       login(request, user)
       return HttpResponseRedirect(reverse('social:home'))
   else:
       return HttpResponseBadRequest("The combination of username and password does not exist.")

#  original home
# def home(request):
#     return HttpResponse('This is not the home page you are looking for.')

@login_required
def home(request):
    posts = Post.objects.all()
    return render(request, 'social/home.html', {'posts': posts})

def add_post(request):
    pass

social/templates/social/home.html
<html>
  <head>
    <title> Social </title>
  </head>
  <body>
    <div id='new-post'>
      <h1> Write a new post </h1>
      <form action="{% url 'social:add_post' %}" method="post" id='new-post-form'>
      {% csrf_token %}
        <textarea name='text' form='new-post-form' required placeholder="Write your post here..."></textarea>
        <input type='submit'/>
      </form>
    </div>


    {% for post in posts %}
    <div class='post' id="{{post.id}}">
      <p>{{post.text}}</p>
      <p>{{post.date_time}}</p>
    </div>
    {% endfor %}
  </body>
</html>

social/templates/social/index.html
<html>
  <head>
    <title> Welcome to Social! </title>
  </head>
  <body>
    <h1> Welcome to Social, the least useful social network! </h1>
    <h2> Please sign in to continue </h2>

    <form action="{% url 'social:login' %}" method="post">
      {% csrf_token %}
      <input required type="text" name="username" id="username-input">
      <label for="username-input">Username</label> <br />
      <input required type="password" name="password" id="password-input">
      <label for="password-input">Password</label> <br />
      <button type="submit"/>Log in</button>
    </form>
  </body>
</html>